### ISSUE TITLE
bufferToHexArray?

### ISSUE THREAD

**Issue by martin-braun** [sant123/hextools#2]
Having array output would make it more flexible, i.e. I want to turn the value `0x1234` into "0x12 0x34", which would be easy if I could convert it into a string array of `[ "12", "34" ]`.

Like so: https://stackoverflow.com/a/39225475/1540350

**Comment by sant123** [comment]
I think you could use https://deno.land/std@0.197.0/encoding/hex.ts?doc=

**Comment by martin-braun** [comment]
@sant123 Well. `hex.encode()` turns a Uint8Array (of some encoded data) into an Uint8Array of its hex encoding, which is double its size. `hex.decode()` does the opposite. 

So, coming from something like "0x1234" I'd need to do this kind of madness:

```ts
import * as hex from "https://deno.land/std@0.192.0/encoding/hex.ts"; 
const encoder = new TextEncoder();
const hexString = "0x1234";
const hexData: Uint8Array = encoder.encode(hexString.split('x')[1]);
console.log(hexData); // [ 49, 50, 51, 52 ]
const rawData: Uint8Array = hex.decode(hexData)
console.log(rawData); // [ 18, 52 ] (equals to [ 0x12, 0x34 ])
const hexArrayAsString: string = "0x" +
  Array.from(rawData, (c) => c.toString(16)).join(
    ` 0x`
  );
console.log(hexArrayAsString); // "0x12 0x34"
```

So basically turning my string into a buffer which is just data that ultimately is double-encoded (since we turned a hex into its hex representation). I then decode it to have the buffer of the raw data which I can iterate and convert into hex strings via `c.toString(16)`. 

It's probably just easier to iterate over my hexString and `splice(0, 2)` from it.

Neither solution is straight forward. I think it would be a great addition to this library to have something like this built in.

**Comment by sant123** [comment]
So basically you would want this as a result right? 

<img width="581" alt="image" src="https://github.com/sant123/hextools/assets/7959437/eb6b913a-16e6-4b23-87e5-add399cb9036">

I'm also curious what is your use case in this?

**Comment by martin-braun** [comment]
Yes, something like that indeed.

> I'm also curious what is your use case in this?

I'm flavoring a C++ project in which a hex string will be generated from a built binary in the format "0x123456789A..." which I then need to replace in a variable within a `.cpp` as a hex array, i.e. `inline constexpr boost::uuids::uuid const MY_VAR = {{ 0x12, 0x34 ...` followed by a rebuilt of such library with the adjusted C++ file.

All done automatically.

**Comment by sant123** [comment]
I see, well it seems this feature would probably suit for your project only. I can add it to the library if this case can be used in more of one project and for other users. That said, I'm going to share the code here and lets see if more people get interested in this feature, in that case I will create a PR for this.

```ts
function hexToHexPairs(hex: string): string[] {
  if (hex.length % 2 != 0) {
    throw new TypeError(
      "Expecting an even number of characters in the hexString",
    );
  }

  const bad = hex.match(/[G-Z\s]{2}/gi);

  if (bad) {
    throw new TypeError(`Found non-hex characters [${bad.join()}]`);
  }

  const pairs = hex.match(/[\dA-F]{2}/gi)!;

  return pairs;
}
```

**Comment by martin-braun** [comment]
Fair enough! :)
